"use client";
import {ArrowRight,BookOpen,FilePlus2,FolderOpen,Layers,GraduationCap,Sparkles,Zap,SlidersHorizontal} from 'lucide-react';
import type {Deck,StudySettings} from '@/lib/study/types';

export function StudyHome({deck,cards,questions,lessons,busy,pace,onPace,onUpload,onRestore,onSample,onContinue,onManage}:{deck:Deck|null;cards:number;questions:number;lessons:number;busy:boolean;pace:StudySettings['pace'];onPace:(pace:'quick'|'thorough')=>void;onUpload:()=>void;onRestore:()=>void;onSample:()=>void;onContinue:(tab?:string)=>void;onManage:()=>void}){
 return <div className="study-home">
  <section className="home-hero"><div><p className="eyebrow">A LITTLE CURIOSITY. A LOT MORE CLARITY.</p><h1>Your next <em>aha.</em><br/>Starts here.</h1><p className="home-lead">Turn your course material into something you actually understand. Read less. Recall more. Make it yours.</p><div className="actions"><button className="button home-primary" disabled={busy} onClick={onUpload}><FilePlus2 size={19}/>{deck?'Add study files':'Upload study material'}<ArrowRight size={18}/></button><button className="text-button" disabled={busy} onClick={onRestore}><FolderOpen size={18}/>Open a saved pack</button></div><p className="small muted">PDFs & PowerPoints · Local AI · No API key needed</p></div>
   <div className="home-illustration" aria-label="Example study card"><span className="home-orbit">LEARN IT. OWN IT.</span><div className="paper-back"/><div className="paper-front"><div className="paper-heading"><Layers size={19}/><span>ONE IDEA AT A TIME</span><Sparkles size={18}/></div><p>Why does testing<br/>yourself work?</p><div className="paper-answer">Pulling an idea from memory makes it easier to find next time.</div><div className="paper-footer"><span>EXAMPLE FLASHCARD</span><span>01 / 06</span></div></div><span className="home-sticker"><Zap size={16}/>Make it click.</span></div>
  </section>
  {deck&&<section className="home-current"><div className="home-section-title"><div><p className="mini-label">PICK UP WHERE YOU LEFT OFF</p><h2>{deck.name}</h2></div><button className="text-button" disabled={busy} onClick={onManage}><SlidersHorizontal size={16}/>Manage pages</button></div><div className="home-stats"><span><FilePlus2 size={17}/><strong>{deck.slides.length}</strong> pages</span><span><BookOpen size={17}/><strong>{lessons}</strong> explanations</span><span><Layers size={17}/><strong>{cards}</strong> flashcards</span><span><GraduationCap size={17}/><strong>{questions}</strong> questions</span></div><div className="actions"><button className="button" onClick={()=>onContinue()}>Continue studying<ArrowRight size={16}/></button>{cards>0&&<button className="button outline" onClick={()=>onContinue('cards')}>Review flashcards</button>}{questions>0&&<button className="button outline" onClick={()=>onContinue('quiz')}>Take a quiz</button>}</div><p className="small muted">Your current collection stays here while the app is open. Save a study pack to keep it for later.</p></section>}
  <section className="home-bottom"><div className="home-mode"><p className="mini-label">GO AT YOUR PACE</p><h2>A quick start or a deeper dive.</h2><div className="pace-switch" role="group" aria-label="Study generation pace"><button aria-pressed={pace==='quick'} disabled={busy||!!deck?.sample} onClick={()=>onPace('quick')}><Zap size={18}/><strong>Quick</strong><span>Key ideas. Short explanations. Less waiting.</span></button><button aria-pressed={pace==='thorough'} disabled={busy||!!deck?.sample} onClick={()=>onPace('thorough')}><BookOpen size={18}/><strong>Thorough</strong><span>More detail, examples, and practice.</span></button></div></div><div className="home-try"><span className="sample-icon"><GraduationCap size={23}/></span><p className="mini-label">TAKE A LOOK AROUND</p><h2>Meet your study studio.</h2><p>Try a ready-made lesson on memory and learning. Flip a card, test an idea, see what clicks.</p><button className="text-button" disabled={busy||!!deck} onClick={onSample}>{deck?'A collection is already open':'Explore a sample lesson'}{!deck&&<ArrowRight size={16}/>}</button></div></section>
 </div>;
}
